#!/usr/bin/env bash
#
# Build Libron locally inside the fntbld container via Podman.
#
# This mirrors the CI build: it mounts the repository into the prebuilt
# fntbld image (which bundles FontForge, ttfautohint, fonttools, brotli,
# and skia-pathops) and runs build.py. Generated fonts appear in ./out
# on the host.
#
# Usage:
#   ./local-build.sh                   # full build incl. Kobo and CrossPoint
#   ./local-build.sh --without-kobofix # skip generating Kobo (KF) variants
#   ./local-build.sh --without-crosspoint # skip CrossPoint bundles
#   ./local-build.sh --customize       # any build.py flags are passed through
#
# Kobo and CrossPoint variants are generated by default here. build.py takes
# --with-kobofix and --with-crosspoint to enable them. This wrapper accepts
# --without-kobofix and --without-crosspoint to skip them.
#
set -euo pipefail

IMAGE="${FNTBLD_IMAGE:-ghcr.io/nicoverbruggen/fntbld-oci:latest}"

# Resolve the repository root (directory of this script) so the build works
# no matter where it is invoked from.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if ! command -v podman >/dev/null 2>&1; then
  echo "ERROR: podman not found. Install Podman from https://podman.io" >&2
  exit 1
fi

echo "Building Libron with ${IMAGE}"
echo

# Kobo fix is on by default; let the user opt out with --without-kobofix.
# build.py uses --with-kobofix and --with-crosspoint, so translate and pass
# every other argument through untouched.
with_kobofix=1
with_crosspoint=1
args=()
for arg in "$@"; do
  case "${arg}" in
    --without-kobofix) with_kobofix=0 ;;
    --with-kobofix)    with_kobofix=1 ;;
    --without-crosspoint) with_crosspoint=0 ;;
    --with-crosspoint)    with_crosspoint=1 ;;
    *)                 args+=("${arg}") ;;
  esac
done

if [ "${with_kobofix}" -eq 1 ]; then
  args+=("--with-kobofix")
fi
if [ "${with_crosspoint}" -eq 1 ]; then
  args+=("--with-crosspoint")
fi

podman run --rm \
  -v "${REPO_DIR}":/work:z \
  -w /work \
  "${IMAGE}" \
  python3 build.py ${args[@]+"${args[@]}"}
