#!/usr/bin/env bash
#
# Build Libron locally inside the fntbld container via Podman.
#
# This mirrors the CI build: it mounts the repository into the prebuilt
# fntbld image (which bundles FontForge, ttfautohint, fonttools, brotli,
# and skia-pathops) and runs build.py. Generated fonts appear in ./out
# on the host.
#
# Usage:
#   ./local-build.sh                   # full build incl. Kobo (KF) variants
#   ./local-build.sh --without-kobofix # skip generating Kobo (KF) variants
#   ./local-build.sh --customize       # any build.py flags are passed through
#
# Kobo (KF) variants are generated by default here. build.py itself defaults
# to off and takes --with-kobofix; this wrapper flips that default for local
# builds and accepts --without-kobofix to opt out.
#
set -euo pipefail

IMAGE="${FNTBLD_IMAGE:-ghcr.io/nicoverbruggen/fntbld-oci:latest}"

# Resolve the repository root (directory of this script) so the build works
# no matter where it is invoked from.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if ! command -v podman >/dev/null 2>&1; then
  echo "ERROR: podman not found. Install Podman from https://podman.io" >&2
  exit 1
fi

echo "Building Libron with ${IMAGE}"
echo

# Kobo fix is on by default; let the user opt out with --without-kobofix.
# build.py only understands --with-kobofix, so translate accordingly and pass
# every other argument through untouched.
with_kobofix=1
args=()
for arg in "$@"; do
  case "${arg}" in
    --without-kobofix) with_kobofix=0 ;;
    --with-kobofix)    with_kobofix=1 ;;
    *)                 args+=("${arg}") ;;
  esac
done

if [ "${with_kobofix}" -eq 1 ]; then
  args+=("--with-kobofix")
fi

podman run --rm \
  -v "${REPO_DIR}":/work:z \
  -w /work \
  "${IMAGE}" \
  python3 build.py ${args[@]+"${args[@]}"}